# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:
- script: echo Integration Tests
  displayName: 'Run a one-line script'
- task: Maven@3
  continueOnError: true
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: AllureGenerate@1
  continueOnError: true
  inputs:
    resultsDir: 'target/allure-results'
    targetDir: 'allure-report/$(Build.BuildNumber)'
- script: |
    echo Add other tasks to build, test, and deploy your project and.
    aws s3 cp /Users/guilhermerogatto/Documents/vsts-agent-osx-x64-2.186.1/_work/2/s/allure-report/$(Build.BuildNumber) s3://allure-test-integrate-azure-new/$(Build.BuildNumber)/ --recursive --acl public-read
    echo http://allure-test-integrate-azure-new.s3-website-sa-east-1.amazonaws.com/$(Build.BuildNumber)/index.html
  displayName: 'Run a multi-line script'